#!/bin/bash

# Instructions to push fichat-rag to GitHub

echo "Follow these steps to push fichat-rag to your GitHub account:"
echo ""
echo "1. Create a new repository on GitHub:"
echo "   - Go to https://github.com/new"
echo "   - Repository name: fichat-rag"
echo "   - Description: A production-ready RAG framework extracted from fiChat"
echo "   - Keep it public or private as you prefer"
echo "   - DO NOT initialize with README, .gitignore, or license"
echo ""
echo "2. After creating the repository, run these commands:"
echo ""
echo "   # Add your GitHub repository as origin"
echo "   git remote add origin https://github.com/tkim/fichat-rag.git"
echo ""
echo "   # Push the code"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "Alternative: If you prefer using SSH:"
echo "   git remote add origin git@github.com:tkim/fichat-rag.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "3. Your repository will be available at:"
echo "   https://github.com/tkim/fichat-rag"